name: Publish Helm Chart to OCI

on:
  workflow_dispatch:

jobs:
  publish-helm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Package Helm chart
      run: |
        mkdir -p packaged
        helm package deploy/helm/trivy-operator-dashboard --destination packaged

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CHARTS_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

    - name: Push chart to OCI
      run: |
        CHART_PACKAGE=$(ls packaged/*.tgz)
        helm push $CHART_PACKAGE oci://ghcr.io/raoulx24/charts
